// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN1lXPquZX7L5nEVv0qcd_Ylrd-kjNymo',
    appId: '1:76270072251:web:5594b7a999cf3101e5d49e',
    messagingSenderId: '76270072251',
    projectId: 'dmgrs-c983c',
    authDomain: 'dmgrs-c983c.firebaseapp.com',
    storageBucket: 'dmgrs-c983c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ZoK7-t_VthdL3_PQpONhdGHYlih7ENI',
    appId: '1:76270072251:android:243ac72ff0db5600e5d49e',
    messagingSenderId: '76270072251',
    projectId: 'dmgrs-c983c',
    storageBucket: 'dmgrs-c983c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT1eZVjfUBW9z_vSA6RiJ342gg1BmWQqs',
    appId: '1:76270072251:ios:3f96efb730111d2ae5d49e',
    messagingSenderId: '76270072251',
    projectId: 'dmgrs-c983c',
    storageBucket: 'dmgrs-c983c.firebasestorage.app',
    iosBundleId: 'com.dmgrs.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT1eZVjfUBW9z_vSA6RiJ342gg1BmWQqs',
    appId: '1:76270072251:ios:3f96efb730111d2ae5d49e',
    messagingSenderId: '76270072251',
    projectId: 'dmgrs-c983c',
    storageBucket: 'dmgrs-c983c.firebasestorage.app',
    iosBundleId: 'com.dmgrs.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN1lXPquZX7L5nEVv0qcd_Ylrd-kjNymo',
    appId: '1:76270072251:web:5594b7a999cf3101e5d49e',
    messagingSenderId: '76270072251',
    projectId: 'dmgrs-c983c',
    authDomain: 'dmgrs-c983c.firebaseapp.com',
    storageBucket: 'dmgrs-c983c.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDN1lXPquZX7L5nEVv0qcd_Ylrd-kjNymo',
    appId: '1:76270072251:web:5594b7a999cf3101e5d49e',
    messagingSenderId: '76270072251',
    projectId: 'dmgrs-c983c',
    authDomain: 'dmgrs-c983c.firebaseapp.com',
    storageBucket: 'dmgrs-c983c.firebasestorage.app',
  );
}
